### ISSUE TITLE
有票時沒有視窗通知

### ISSUE THREAD

**Issue by karakarasuuuu** [AnselCh/ticket_refresh#8]
如題，照著指示從 source code 建立執行檔後執行，遇到有票時也沒有辦法跳出視窗。

**Comment by AnselCh** [comment]
source code已修正~

**Comment by karakarasuuuu** [comment]
試了一下還是不行耶 0.0 一樣沒有視窗彈出來
還是視窗會自己關閉？剛剛剛好不在電腦前

**Comment by karakarasuuuu** [comment]
哦等一下我好像知道問題在哪了

**Comment by karakarasuuuu** [comment]
是我自己耍笨沒把視窗提醒的選項反白 XD 有點不直觀

**Comment by AnselCh** [comment]
你可以先綁line權杖看看
我剛剛測試提醒視窗是可以的，不過是用假資料測試，因為都撈不到票XD
我的OS:Win11
Python 3.11.4
